---
- name: Create EC2 
  hosts: localhost
  gather_facts: no
  vars:
    region: "ap-south-1"
    ami_id: "ami-02b8269d5e85954ef"  # Example AMI ID (Ubuntu 20.04 LTS)
    instance_type: "t3.micro"
    key_name: "project-passwrd"  # Replace with your actual SSH key pair name
    security_group_name: "my-sg1"
    subnet_id: "subnet-00e7b2b5cec543c9c"  # Replace with your subnet ID

  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Security"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"  # SSH access
        state: present
      register: sg

    - name: Create an EC2 instance
      amazon.aws.ec2_instance:
        name: "MyEC2test"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        security_groups:
          - "{{ sg.group_name }}"
        subnet_id: "{{ subnet_id }}"
        count: 1
        wait: yes
      register: ec2_instance
